name: Simple CICD

on:
  push:

jobs:
  build:
    uses: InsightDI/mrb-terraform-azure-net-gha/.github/workflows/dotnetcore.yml@mrb/initial
    with:
      app-path: app
  deploy-dev:
    needs: build
    uses: InsightDI/mrb-terraform-azure-net-gha/.github/workflows/terraform.yml@mrb/initial
    with:
      env: dev
      tf-path: infra/terraform
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
#   deploy-test:
#     needs: deploy-dev 
#     uses: hca-ccoe/demo-tfc-workflow/.github/workflows/terraform.yml@development/update-workflows
#     with:
#       env: test
#     secrets:
#       TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
#   deploy-staging:
#     needs: deploy-test 
#     uses: hca-ccoe/demo-tfc-workflow/.github/workflows/terraform.yml@development/update-workflows
#     with:
#       env: staging
#     secrets:
#       TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
#   deploy-prod:
#     needs: deploy-staging 
#     uses: hca-ccoe/demo-tfc-workflow/.github/workflows/terraform.yml@development/update-workflows
#     with:
#       env: prod
#     secrets:
#       TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
