name: eShopOnWeb Rich Code Navigation

on:
  workflow_call:
    inputs:
      app-path:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
        default: build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Build
      run: dotnet build ${{ inputs.app-path }} -c Release
    
    - name: Test
      run: dotnet test ${{ inputs.app-path }} -c Release

    - name: Publish 
      run: dotnet publish ${{ inputs.app-path }} -c Release -o Build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.app-path }}/Build
        if-no-files-found: error