name: eShopOnWeb Rich Code Navigation

on:
  workflow_call:
    inputs:
      app-path:
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build ${{ inputs.app-path }}/eShopOnWeb.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ${{ inputs.app-path }}/eShopOnWeb.sln --configuration Release