name: eShopOnWeb Rich Code Navigation

on:
  workflow_call:
    inputs:
      app-path:
        required: true
        type: string

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build with dotnet
      run: |
        cd ${{ inputs.app-path }}
        dotnet build ./eShopOnWeb.sln --configuration Release

    - uses: microsoft/RichCodeNavIndexer@v0.1
      with:
        repo-token: ${{ github.token }}