name: 'Matrix Testing'

on:
  workflow_call:
    inputs:
      matrix_output:
        required: true
        type: string

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    name: matrix job
    environment: ${{ matrix.environment }}

    concurrency:
      group: ${{ matrix.environment }}
      cancel-in-progress: false
    strategy:
      matrix: ${{ fromJson(inputs.matrix_output) }}
      max-parallel: 1
    steps:
      - run: |
          echo ${{ matrix.environment }}
          echo ${{ matrix.depends_on[0] }}
          echo ${{ matrix.tf_lint }}
          echo ${{ matrix.os }}