name: 'Terraform'

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      tf-path:
        required: true
        type: string
      output-vars:
        required: false
        type: string
    secrets:
      TF_API_TOKEN:
        required: true
    outputs:
      resource_group_id:
        description: "Resource group Id"
        value: ${{ jobs.terraform-outputs.outputs.resource_group_id }}
      app_service_hostname:
        description: "Web app hostname"
        value: ${{ jobs.terraform-outputs.outputs.app_service_hostname }}


jobs:
  terraform-outputs:
    name: 'Terraform Provisioning - Outputs'
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    defaults:
      run:
        shell: bash

    outputs:
      resource_group_id: ${{ steps.tf_outputs.outputs.resource_group_id }}
      app_service_hostname: ${{ steps.tf_outputs.outputs.app_service_hostname }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - run: echo ${{ inputs.output-vars }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ inputs.tf-path }}

    - name: Terraform Outputs
      id: tf_outputs
      run: ${{ inputs.output-vars }}
      working-directory: ${{ inputs.tf-path }}

    - run: |
        terraform output -raw resource_group_id
        terraform output -raw app_service_hostname