name: 'Terraform Provisioning'

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      tf-path:
        required: true
        type: string
    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  terraform:
    name: 'Terraform Provisioning'
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Replace Tokens - providers.tf
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["infra/terraform/providers.tf"]'
      env:
        environment: ${{ inputs.env }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ inputs.tf-path }}

    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true
      working-directory: ${{ inputs.tf-path }}

    - name: Terraform Plan
      run: terraform plan -var "environment=${{ inputs.env }}"
      working-directory: ${{ inputs.tf-path }}

    - name: Terraform Apply
      # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      working-directory: ${{ inputs.tf-path }} 
